# Generated by Django 2.1.7 on 2019-03-22 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190322_0543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishpref',
            name='user',
        ),
        migrations.RemoveField(
            model_name='restaurantpref',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nutrition',
        ),
        migrations.RemoveField(
            model_name='user',
            name='price',
        ),
        migrations.AddField(
            model_name='user',
            name='dpf',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.DishPref'),
        ),
        migrations.AddField(
            model_name='user',
            name='rpf',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.RestaurantPref'),
        ),
    ]
