# Generated by Django 2.1.7 on 2019-03-22 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190322_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dpf',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.DishPref'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rpf',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.RestaurantPref'),
        ),
    ]
