# Generated by Django 2.1.7 on 2019-03-22 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190322_0600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dpf',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rpf',
        ),
        migrations.AddField(
            model_name='dishpref',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurantpref',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='nutrition',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dishpref',
            name='nutrition',
            field=models.IntegerField(default=0),
        ),
    ]
