# Generated by Django 2.1.7 on 2019-03-22 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190322_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='name',
            new_name='rest_name',
        ),
    ]
