# Generated by Django 2.1.7 on 2019-03-22 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190322_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishpref',
            options={'verbose_name_plural': 'Dish Preferences History'},
        ),
        migrations.AlterModelOptions(
            name='restaurantpref',
            options={'verbose_name_plural': 'Restaurant Preferences History'},
        ),
        migrations.RemoveField(
            model_name='restaurantpref',
            name='cuisine',
        ),
        migrations.AddField(
            model_name='restaurantpref',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='dishpref',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
