# Generated by Django 2.1.7 on 2019-03-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190322_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishpref',
            name='rating',
        ),
        migrations.AddField(
            model_name='dishpref',
            name='eaten_dish',
            field=models.BooleanField(default=False),
        ),
    ]
